"""empty message

Revision ID: 212fcd32f1c3
Revises: 412e691d4c3d
Create Date: 2020-08-27 16:42:22.499316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '212fcd32f1c3'
down_revision = '412e691d4c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='group')
    op.drop_table('group_member')
    op.drop_table('group')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_member',
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('mailbox_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='group_member_ibfk_1'),
    sa.ForeignKeyConstraint(['mailbox_id'], ['mailbox.id'], name='group_member_ibfk_2'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('group',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('ctx_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ox_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ctx_id'], ['context.id'], name='group_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'group', ['name'], unique=True)
    # ### end Alembic commands ###
