"""empty message

Revision ID: 412e691d4c3d
Revises: 9d327ee3e70c
Create Date: 2020-08-07 09:41:47.657370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '412e691d4c3d'
down_revision = '9d327ee3e70c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('ctx_id', sa.Integer(), nullable=True))
    op.add_column('group', sa.Column('ox_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group', 'context', ['ctx_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'ox_id')
    op.drop_column('group', 'ctx_id')
    # ### end Alembic commands ###
