"""empty message

Revision ID: 975e8e15c976
Revises: 
Create Date: 2020-07-27 14:25:29.740803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '975e8e15c976'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mailbox', sa.Column('plan_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mailbox', 'plan_id')
    # ### end Alembic commands ###
