"""empty message

Revision ID: 9d327ee3e70c
Revises: aaba5ffd78b5
Create Date: 2020-08-07 09:14:05.551864

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9d327ee3e70c'
down_revision = 'aaba5ffd78b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_index('email', table_name='group')
    op.create_unique_constraint(None, 'group', ['name'])
    op.drop_column('group', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('email', mysql.VARCHAR(length=30), nullable=False))
    op.drop_constraint(None, 'group', type_='unique')
    op.create_index('email', 'group', ['email'], unique=True)
    op.drop_column('group', 'name')
    # ### end Alembic commands ###
