"""empty message

Revision ID: aaba5ffd78b5
Revises: 9b6ca57205a3
Create Date: 2020-08-07 08:45:12.163486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaba5ffd78b5'
down_revision = '9b6ca57205a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('context', sa.Column('admin', sa.String(length=200), nullable=True))
    op.add_column('context', sa.Column('password', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('context', 'password')
    op.drop_column('context', 'admin')
    # ### end Alembic commands ###
