"""empty message

Revision ID: d4061d895922
Revises: 
Create Date: 2020-10-17 19:54:05.547876

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd4061d895922'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'created')
    op.drop_column('customer', 'changed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('changed', mysql.DATETIME(), nullable=True))
    op.add_column('customer', sa.Column('created', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
