"""empty message

Revision ID: e7f180299d16
Revises: 047da9168b45
Create Date: 2020-10-17 20:55:02.710844

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7f180299d16'
down_revision = '047da9168b45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('config', sa.String(length=300), nullable=True))
    op.add_column('plan', sa.Column('ma', sa.String(length=50), nullable=True))
    op.drop_column('plan', 'oxid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plan', sa.Column('oxid', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('plan', 'ma')
    op.drop_column('plan', 'config')
    # ### end Alembic commands ###
